WIP - account requirement and instructions
VueVixens/docs pull request #146
Opened 2020-06-24 12:59 UTC by artikgupta

This a work in progress. It looks like there is some linting(?) being done, but I don't know if it's coming from me or Front End Foxes. 
 @MicheleCynowicz Can you help me figure this out?

2020-06-24 23:16 UTC, MicheleCynowicz commented
This is interesting @artikgupta 🤔  it looks like this might be coming from some automatic linter you have running in your IDE (that's your code editor application, or **I**ntegrated **D**evelopment **E**nvironment).

What IDE are you using? I am usually using VS Code when I work, and it is possible to have automatic linting installed with a VS Code extension.

We probably should add our own linting file and linting rules to this repository so that changes we don't want from others' IDEs will be marked as unable to merge. In the meantime we can review your IDE setup and I can show you how to undo these types of changes during our next Pair Programming session.

2020-06-25 18:18 UTC, artikgupta commented
I am using vs code. Looking forward to the next session. Thank you.

2020-07-04 12:47 UTC, artikgupta commented
This PR addresses the acceptance criteria for #140 
@MicheleCynowicz ready for review

2020-07-06 13:50 UTC, MicheleCynowicz commented
This looks good Arti! Thanks for this. I am going to leave this PR open for a short while so I can compare how the page renders with your linter's added features. I like some of the things that have been added, but I need to make sure Vuepress does the right thing with them.

2020-08-15 12:28 UTC, MicheleCynowicz commented on workshops/vue/minis/mini6.md
> +  render: (h) => h(App),
let's remove these lint changes so that this code block remains untouched

2020-08-15 12:29 UTC, MicheleCynowicz commented on workshops/vue/minis/mini6.md
> +  Quiz;
remove this lint-provided semi-colon, I don't think that's the correct syntax for this

2020-08-15 12:33 UTC, MicheleCynowicz commented on workshops/vue/minis/mini6.md
> +    ...{
revert this change, the linter has picked this ellipsis up as a spread operator, but that's incorrect, the ellipsis should be on it's own line.

2020-08-15 12:38 UTC, MicheleCynowicz commented on workshops/vue/minis/mini6.md
> +>
remove the closing `</div>` and `</template>` tags here that the linter added, as this is not a complete code block for teaching purposes.

2020-08-15 12:46 UTC, MicheleCynowicz requested changes
just a few things the linter "fixed" that aren't good fixes for our workshop code. If these can be removed, then the PR is ready to merge 🎉

2020-09-18 12:16 UTC, artikgupta commented
This PR had lots of issues so I have decided to raise a new PR (#178) to address the same issue (#140).

2020-09-18 12:16 UTC, closed without merging