Computed props nano
VueVixens/docs pull request #54
Opened 2019-01-13 04:28 UTC by marina-mosti

2019-01-18 02:21 UTC, jlooper reviewed
This looks terrific. I really like the simplicity although the concept is hard to grasp. Having the explanation in a tip at the end is probably good, although I suppose we could add it mid-stream.

Barring comments from @NataliaTepluhina I'd like to merge / copyedit etc.

2019-01-18 06:27 UTC, NataliaTepluhina requested changes

2019-01-18 06:33 UTC, NataliaTepluhina commented
@immarina thank you for your hard work! I really love the clear explanations you give on computed properties and how they work, In the meantime, I would probably ask you to replace an example: with current one we don't have any reactive dependencies. So, in fact, this computed property will _never_ update and we can't show one of the core features of computed: recalculating on dependency change.

2019-01-19 03:36 UTC, immarina commented on workshop/nanos/nano4.md
> +Rule of thumb is, whenever you need to `calculate` a value, or change a value in any way - use computed properties.
Will rephrase to
`Rule of thumb is, whenever you need to `calculate` a value reactively when another property changes - use computed properties.`

2019-01-19 04:33 UTC, jlooper reviewed
This looks better to me, to show an actual calculation against a date, and something a student can watch working in real time. I leave it to @NataliaTepluhina for final approvals

2019-01-20 16:52 UTC, NataliaTepluhina commented
Thank you for changing it, @immarina ! Looks good to me now 👍

2019-01-20 16:52 UTC, NataliaTepluhina approved these changes

2019-01-20 17:26 UTC, merged