updated vuetify installation instructions (de)
VueVixens/docs pull request #89
Opened 2019-10-01 08:15 UTC by LadyMashiro

Hey there. I updated the  Vuetify installation instructions for the german version of the full-day workshop, like requested in [Pullrequest 86](https://github.com/VueVixens/docs/pull/86) and I also used vuetify version ^2.0.19 which was requested from Jen in the PR review from 86.

2019-10-04 12:35 UTC, vicmeow requested changes
Looks good, just some text that needs to be removed or still needs translating.

2019-10-04 12:35 UTC, vicbergquist commented on de/workshop/full-day/ch1.md
> +From this initializer file, you will be able to import Vuetify's themes, components, and CSS with just two mentions in your `main.js` file.
This English should be removed I guess?

2019-10-04 12:35 UTC, vicbergquist commented on de/workshop/full-day/ch1.md
> +Since this initializes the Vue instance in your app, you will need to add `vuetify` here to pass along all the design goods from your Vuetify plugin file.
Still needs translating?

2019-10-05 10:05 UTC, LadyMashiro commented on de/workshop/full-day/ch1.md
> +Since this initializes the Vue instance in your app, you will need to add `vuetify` here to pass along all the design goods from your Vuetify plugin file.
Thanks @vicbergquist, I updated those :)

2019-10-05 10:41 UTC, vicmeow approved these changes

2019-10-05 10:41 UTC, merged